services:
  mongo:
    image: mongo
    container_name: mongo-licences-manager
    restart: always
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend-licences-manager
    restart: always
    networks:
      - licences_manager_network
    environment:
      - MONGO_URL=mongodb://mongo:27017/licenceManagerDB
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-licences-manager
    restart: always
    networks:
      - licences_manager_network
    ports:
      - "80:80"

volumes:
  mongo-data:


networks:
  licences_manager_network:
    external: true
