services:
  caddy:
    image: caddy
    container_name: caddy-licences-manager
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - backend

  mongo:
    image: mongo
    container_name: mongo-licences-manager
    restart: always
    networks:
      - backend
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    container_name: backend-licences-manager
    restart: always
    networks:
      - backend
    environment:
      - MONGO_URL=mongodb://mongo:27017/licenceManagerDB
    depends_on:
      - mongo
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-licences-manager
    restart: always
    networks:
      - backend
    ports:
      - "8080:80"

volumes:
  mongo-data:


networks:
  backend:
    driver: bridge
